name: CI/CD to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job completes before deployment

    steps:
    # Checkout the code again in the deploy job
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up AWS CLI
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
      
    # Install the EB CLI using pip
    - name: Install EB CLI
      run: |
        python -m pip install --upgrade pip
        pip install awsebcli
    
    # Deploy to EB
    - name: Init EB CLI
      run: |
        eb init --platform "Node.js 18 running on 64bit Amazon Linux 2023" --region ap-southeast-1 Undress-game-server
    - name: Choose EB Env
      run: |
        eb use Undress-game-server-env
    - name: Deploy to Elastic Beanstalk
      run: |
        eb deploy 